export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const SET_AUTH_LOGOUT = 'SET_AUTH_LOGOUT';
export const SET_AUTH_LOGIN = 'SET_AUTH_LOGIN';
export const SET_AUTH_REGISTER = 'SET_AUTH_REGISTER';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

